<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Title>g0v0!resources</Title>
    <Product>g0v0!resources</Product>
    <Company>GooGuTeam; ppy Pty Ltd (original)</Company>
  </PropertyGroup>
  <PropertyGroup Label="Nuget">
    <Title>g0v0!resources</Title>
    <PackageId>ppy.osu.Game.Resources</PackageId>
    <Authors>GooGuTeam; ppy Pty Ltd</Authors>
    <PackageLicenseUrl>https://github.com/GooGuTeam/g0v0-resources/blob/master/LICENCE.md</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/GooGuTeam/g0v0-resources</PackageProjectUrl>
    <RepositoryUrl>https://github.com/GooGuTeam/g0v0-resources</RepositoryUrl>
    <PackageReleaseNotes>Automated release.</PackageReleaseNotes>
    <copyright>Copyright (c) 2019 ppy Pty Ltd; Copyright (c) 2026 GooGuTeam</copyright>
    <PackageTags>g0v0 game resources</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Beatmaps\**\*" />
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Skins\**\*" />
    <EmbeddedResource Include="Shaders\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="Tracks\**\*" />
  </ItemGroup>
  <ItemGroup>
    <!-- Resolves references to LocalisableString. -->
    <PackageReference Include="ppy.osu.Framework" Version="2026.629.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
